Repository gweicz/bankless-cz, pull requests merged in 2021-03, with the labels that each got.

#43 refactor: update README
  README.md
Labels: documentation

#48 Kodex SubPage
  components/Layout/Footer.tsx
  pages/kodex/index.tsx
  pages/kodex/kodex.module.scss
Labels: enhancement

#47 BugFix - Už se nemění barva po najetí takže text je čitelný
  components/Article/Banner.tsx
  components/SocShare.tsx
Labels: bug

#51 deployment update
  .gitignore
  Dockerfile
  README.md
  components/SocShare.tsx
Labels: enhancement
