Repository gweicz/bankless-cz, pull requests merged in 2021-05, with the labels that each got.

#124 Added ostatní tag to megaMenu
  components/Megamenu/Megamenu.tsx
  utils/fetchMenuPosts.ts
Labels: enhancement

#125 BugFix - Megamenu article detail bug
  components/Megamenu/Megamenu.tsx
Labels: bug

#126 Create LICENSE
  LICENSE
Labels: documentation

#127 paginator bugs
  components/HomePage/PostList/PostList.tsx
  constants.ts
  pages/api/posts.ts
  pages/authors/[username].tsx
  pages/index.tsx
  pages/novinky/bitcoin/index.tsx
  pages/novinky/ethereum/index.tsx
  pages/novinky/index.tsx
  pages/novinky/ostatni/index.tsx
  pages/novinky/polkadot/index.tsx
  pages/studium/bitcoin/index.tsx
  pages/studium/ethereum/index.tsx
  pages/studium/index.tsx
  pages/studium/ostatni/index.tsx
  pages/studium/polkadot/index.tsx
Labels: bug

#128 Vojtch cookies
  components/Layout/Cookies.module.scss
  components/Layout/Cookies.tsx
  package.json
  pages/_app.tsx
  pages/hashovky/index.tsx
  pages/kodex/index.tsx
  pages/novinky/[id].tsx
  pages/podminky/index.tsx
  pages/studium/[id].tsx
  utils/google.tsx
  yarn.lock
Labels: bug

#134 YT Video bugFix - responsive
  components/Article/Article.module.scss
Labels: bug
